import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/providers/global";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Exam App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
        <Toaster/>
      </body>
    </html>
  );
}


// Email aya1812@gmail.com
// Password    / Aya123@@@@