import type { Metadata } from "next";
import "./globals.css";
import NextAuthProvider from "@/components/providers/next-auth.provider";

export const metadata: Metadata = {
  title: "Exam App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
